### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kk6axq**
Add stuff so people know not to download this version if they are looking for the REAL Arduino(r)

### CODE REVIEW

**Comment by JohnnyricoMC** [comment]
+1. The naming conflict WILL cause confusion with uninformed new users of the platform that version numbering can never solve.

**Comment by RockyTV** [comment]
+1

**Comment by arthurwolf** [comment]
+1

**Comment by hashashin** [comment]
:+1:

**Comment by jackmaney** [comment]
:+1:

**Comment by simonmorley** [comment]
:8ball:

**Comment by simonmorley** [comment]
f6890207-0925-a4ad-34a821cfa8e85f11

**Comment by IrregularShed** [comment]
:shipit:

**Comment by vivin** [comment]
:+1:

**Comment by lucket** [comment]
:+1:

**Comment by Dakuan** [comment]
:shipit:

**Comment by Chris--A** [comment]
:+1:

**Comment by kk6axq** [comment]
Hey @arduino-org and @arduino-org-team The more time you spend silent, not dealing with "Arduino"(us) as you say, you put more nails into your coffin... It is time you gave us straight no fuss answers to all of our questions. You have over 300 people talking to you and you are all ignoring them... Even if you win in court, you've lost the community, you've lost "Arduino". 
Sincerely,
The Arduino Community

**Comment by MauroMombelli** [comment]
seems like they fixed this (even with proprer credit), the issue can be closed

**Comment by quasto** [comment]
we updated the README.md file in the main branches.
the pull request will be closed, but if you feel appropriate, re-open it

**Pull request closed without merging**
